### ISSUE TITLE
We don't have a project!

### ISSUE THREAD

**Issue by wingsoverglades** [Ramtech-TSA/SD2016#1]

**Comment by djlazz3** [comment]
I think we should look at markets that are not really developed and try to find solutions to some of their problems with software. Also as far as programming itself is concerned i have no idea what language we are going to use but i believe that to make our program better for competition that we should try to make something that doesn't just run on windows(makes it more readily accessible which is one of the things that TSA is scoring). In short probably no vb.net

**Comment by wingsoverglades** [comment]
Alright, so today we'll talk about deciding on a project then we'll choose a language. I also want to get everyone up to speed with this repository.

Since we're working as a group I also want to throw around the idea of having an established code style that everyone can read. Like a certain indent-depth, bracket placement, naming convention, comment placement and the like. It sounds kinda crappy but that's one of the better ways of making sure we all write understandable code.
